### ISSUE TITLE
Proporcionar información más detallada en la búsqueda

### ISSUE THREAD

**Issue by egara** [lemoncrest/kelboy-launcher#1]
Muy buenas.

Me gustaría sugerir un feature request que creo que añadiría una mejora en el uso de la funcionalidad de búsquedas online del launcher.

Sería estupendo que cuando se llevase a cabo la búsqueda apareciera, además del nombre, la plataforma a la que pertenece, ya que búsquedas como por ejemplo Super Mario arrojan muchos resultados pero no se sabe muy bien en qué plataformas se encuentra dispoible.

Muchas gracias y a seguir con ese trabajo tan bueno que estáis haciendo!

**Comment by bitstuffing** [comment]
Hola, gracias, ya que es una funcionalidad de navegación web externa se intentará mostrar más información relacionada con el contenido que ofrezcan las webs externas

**Comment by bitstuffing** [comment]
Se ha subido la funcionalidad en el último commit.
