### ISSUE TITLE
[Spanish] Documentación sobre cómo instalar el launcher en la kelboy desde cero

### ISSUE THREAD

**Issue by loscharlies** [lemoncrest/kelboy-launcher#13]
Realmente no se si debería estar aquí este issue pero no he encontrado otro github vuestro en el que ponerlo así que... lo que me gustaría es disponer no solo del launcher, sino que me gustaría tener la posibilidad de tener los drivers de la kelboy (quien dice drivers dice lo que sea que haga falta) para su correcto funcionamiento si se desea realizar una instalación desde cero, o sea, con una imagen limpia de retropie. ¿Sería posible esto? Realmente supongo que se podría sacarlos de la imagen que tenéis así que... al final solo sería cuestión de tiempo.

**Comment by qu1que** [comment]
Buenas, 

Relacionado con este issue, a mi me interesaría saber como se podría instalar solo el launcher desde cero. Entiendo que sería eliminar el directorio kelboy-launcher y volver a hacer un git clone y a continuación ejecutar el script de instalación, pero no sé si esto que digo es así ó si habría que hacer alguna cosa más a mayores. 

Todo esto viene a cuento de que tengo ya la imágen muy trasteada y no sé si algo tengo mal, ya que a veces el launcher se queda congelado y no me responden los controles. No hay problema, ya que si reinicio vuelve a funcionar todo pero me interesaría poder instalarlo de cero.

**Comment by bitstuffing** [comment]
Los issues tienen que estar relacionados con el launcher. De todas maneras de esta conversación se pueden sacar tareas:

- [ ] Completar el README con información que describa cómo instalar el launcher desde 0

**Comment by loscharlies** [comment]
Buenas, entiendo el cambio del título del issue pero solo a medias, básicamente lo que yo quiero es saber como se hace una imagen desde cero y que funcione todo, tanto wifi como bluetooth y todos los componentes de los que consta la placa, no solo la instalación del launcher como tal. Entonces, si aquí solo se pueden abrir issues para lo que es el launcher, donde deberíamos abrir un issue de este estilo? No hay, y repito, no hay github de lo que es la placa, arduino, etc... debería existir un github del proyecto

**Comment by bitstuffing** [comment]
> Buenas, entiendo el cambio del título del issue pero solo a medias, básicamente lo que yo quiero es saber como se hace una imagen desde cero y que funcione todo, tanto wifi como bluetooth y todos los componentes de los que consta la placa, no solo la instalación del launcher como tal. Entonces, si aquí solo se pueden abrir issues para lo que es el launcher, donde deberíamos abrir un issue de este estilo? No hay, y repito, no hay github de lo que es la placa, arduino, etc... debería existir un github del proyecto

Este repositorio es exclusivo del launcher. 

Un issue, por definición, es un problema exclusivo del proyecto en el que se crea, al igual que tampoco es un lugar para pedir ayuda.

Desde nuestro lado siendo proactivos se ha adaptado el issue a algo que pueda mejorar las cualidades como propone el usuario @qu1que, como es el hecho de dedicarle tiempo a un README mejor y más entendible, y en vez de cerrarse y descartarse se le va a dedicar un tiempo de desarrollo, que a mi juicio puede ayudar a la comunidad, a la mejor comprensión del proyecto y la participación de más usuarios que quieran animarse a programar un launcher. 

Por eso se ha explicado que se concluye con una tarea.

Todas las propuestas en github como en cualquier proyecto abierto pueden ser realizadas a través de su metodología, es decir, debes de hacer un fork personal, implementar cualquier tipo de código o documentación que se te ocurra aportar como mejora, y si deseas realizar un pull request y esperar que los desarrolladores consideren tu contenido apropiado para ser incluido y aprobado. Se te anima a ello.

Terminar con dejar claro, si no te satisface la explicación lo lamentamos profundamente, pero todos los participantes tienen que ceñirse al proyecto, lo considerado como irrelevante o inapropiado es descartado y/o eliminado.

**Comment by loscharlies** [comment]
Gracias por la aclaración aunque no hacía falta... podrías indicarme donde abrir un issue para vuestro proyecto kelboy 2.0?? Sigo sin ver un sitio específico para ello. He ojeado vuestra web y no veo dónde poner este tipo de cosas, el único sitio que encontré fue este... Muchas gracias y agradezco sinceramente la colaboración realizando un README mejorado

**Comment by kelroy1990** [comment]
Charlie, justamente lo que pides está en https://lemoncrest.org/community/resources/products, en la "Kelboy 2.0 Retropie Release 1.0". Es una retropie limpia con los drivers.

En un futuro cercano se hará un github con fw, de ahí podrás sacar más cosas y discutir estos puntos.

**Comment by loscharlies** [comment]
Buenas kelroy, se que existe esa imagen limpia con los drivers instalados pero sinceramente eso no es lo que pido. Me gustaría llegar más allá y hacerlo yo, tener las herramientas para crear mi propia imagen from scratch, sin añadir nada más que los drivers. Si se actualiza el README del launcher con eso y lo que pido yo ya estaría todo. Un saludo ;)
