### ISSUE TITLE
[Spanish] Compatibilidad de Pico-8 a través del launcher

### ISSUE THREAD

**Issue by qu1que** [lemoncrest/kelboy-launcher#14]
Pico8 es un sistema nuevo diseñado para pantallas pequeñas, con muchos juegos más o menos divertidos, muchos de ellos en constante desarrollo. Más info aquí: https://www.lexaloffle.com/pico-8.php

Después de conseguir instalarlo satisfactoriamente en la kelboy (pagando la licencia, ya que no hay otra manera), me encuentro con que no detecta los controles de la kelboy, pero sí funciona conectando un teclado. Leyendo el manual de instrucciones incluido con la descarga me encuentro con lo siguiente:

:: Controller Setup

	PICO-8 uses the SDL2 controller configuration scheme. It will detect common controllers
	on startup and also looks for custom mappings in **sdl_controllers.txt** in the same directory 
	as config.txt. sdl_controllers.txt has one mapping per line.

	To generate a custom mapping string for your controller, **use either the controllermap
	program that comes with SDL2**, or try http://www.generalarcade.com/gamepadtool/

	To find out the id of your controller as it is detected by SDL2, search for "joysticks"
	or "Mapping" in log.txt after running PICO-8. This id may vary under different operating
	systems. See: https://www.lexaloffle.com/bbs/?tid=32130
	
	To set up which keyboard keys trigger joystick buttons presses, use KEYCONFIG.

Se ha remarcado en negrita lo que considero que es la clave para poder hacerlo funcionar, ya que usando la herramienta controllermap de SDL2 se genera una línea que habría que copiar dentro del archivo sdl_controllers.txt (también en negrita) para que así el sistema detecte el arduino de la kelboy y de esa manera poder asignar teclas de teclado con pulsaciones del arduino.

Existe una base de datos de diferentes controles que va incluyendo la gente, pero en ningún caso sale nada similar ó referente a un arduino. 

https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

Alguna idea de como poder generar esa línea de mapeado para el arduino?

**Comment by bitstuffing** [comment]
Me gusta mucho este framework, todo lo que sea mejorar la integración de nuevas plataformas es bienvenido. Lo sigo mucho desde itch.io y tiene muchos juegos versión web, pero no conocía que tenía versión nativa para plataformas Raspberrry Pi. Sería interesante integrarlo con este launcher.

Como idea, habría que integrar los credenciales de cada usuario para que se baje de manera legítima este framework y poder correr los juegos de manera nativa. 

Cambio el nombre del issue a "Compatibilidad de Pico-8 a través del launcher".

Sacamos dos tareas para trabajar en esa base:

- [x] Integrar el cliente oficial desde el launcher para poder descargar de manera legítima

- [x]  Adaptar el joystick.py para que simule las teclas que tenga configurados el framework y que mientras esté activo simule lo que necesita este entorno.

**Comment by bitstuffing** [comment]
Se ha integrado el el anterior commit https://github.com/lemoncrest/kelboy-launcher/commit/88ffcda7d7310971f8c3327fb1c2ea7d9394f120 la máquina pico-8, se procede con el joystick.py

**Comment by bitstuffing** [comment]
Voy a reabrirlo porque hay funcionalidades que se van a implementar que no se mentaron y tienen que ver con la funcionalidad nueva de dar compatibilidad con Pico-8

**Comment by bitstuffing** [comment]
Cerrado por implementar la búsqueda y paginación
