### ISSUE TITLE
[Spanish] Mostrar por orden alfabético el listado de ficheros

### ISSUE THREAD

**Issue by qu1que** [lemoncrest/kelboy-launcher#19]
Sería muy interesante si se pudiesen mostrar en orden alfabético los ficheros, tanto en el menú Launcher/Load Roms como en el menú Programs/Web Browser/roms (esto último no sé si será posible).

**Comment by bitstuffing** [comment]
Se ha añadido un orden en el listado de ficheros locales y se ha subido a la rama master, en cuanto a lo otro es un navegador web, como aparezca el contenido se muestra por lo que se podría hacer pero se rechaza ya que es el orden que establece el anfitrión en su web.
