### ISSUE TITLE
[Spanish] Creación de un script personalizable para poder mapear los botones de la kelboy como teclas de teclado

### ISSUE THREAD

**Issue by qu1que** [lemoncrest/kelboy-launcher#23]
Echando un ojo al script joystick.py incluído en el launcher, se aprecia que está hecho para que funcione solo en el launcher, pero no veo la manera de poder usarlo en algún otro juego que necesite solo teclado. Habría que editarlo de la forma adecuada para cada caso. Por ejemplo, un script para un juego que necesite 3 teclas, otro para otro juego que necesite 5 teclas, etc, etc. 

Evidentemente, teniendo conocimientos avanzados en python se podría hacer, pero como no es mi caso, y seguramente el de mucha gente, me preguntaba si sería posible crear un "script-plantilla" de tal forma que solo haya que indicar qué tecla del teclado se asigna a cada botón. Imagino que cada botón tendrá un código y cada tecla también, simplemente bastaría con relacionar un código con otro

Me refiero básicamente a juegos incluídos en la sección Ports de RetroPie, ya que si el emulador forma parte del proyecto libretro, es posible mapearlo, como por ejemplo el emulador de MSDOS lr-dosbox.

No sé si esto que propongo sería muy complejo o simplemente imposible. Es solo una idea.

**Comment by bitstuffing** [comment]
Implementado y mergeado en el último merge.

Más información en el siguiente enlace:

https://lemoncrest.com/articles?id=17
