### ISSUE TITLE
Los controles de la kelboy dejan de funcionar cuando se conecta algún dispositivo por SSH

### ISSUE THREAD

**Issue by qu1que** [lemoncrest/kelboy-launcher#45]
Al iniciar sesión remota mediante SSH a la kelboy desde otro dispositivo, dejan de funcionar los controles en la propia kelboy. Sería interesante que no ocurriera esto, no sé si será posible.

**Comment by bitstuffing** [comment]
La causa de lo que dices es que al rearrancar el launcher hay un kill que mata a los procesos launcher anteriores, eso se encuentra en el archivo /home/pi/.bashrc. Se puso ahí para que el usuario no tuviera que editar servicios pero no se pensó que alguien entrara con el launcher arrancado, de todas maneras es un issue del sistema, no del propio launcher. Pero por dar una solución:

Hay que reemplazar las líneas que lanzan el launcher por una condición que detecte si estás o no por ssh.

Original:

    cd kelboy-launcher
    ./launcher.sh

Reemplazo:

    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        echo "welcome to kelboy throw ssh session"
	else
	    cd kelboy-launcher
	    ./launcher.sh
	fi

Con eso queda solventado
