### ISSUE TITLE
[Spanish] Mantener pulsada una dirección en la cruceta

### ISSUE THREAD

**Issue by bitstuffing** [lemoncrest/kelboy-launcher#7]
Se requiere una funcionalidad nueva.

Al parecer sería recomendable añadir una nueva funcionalidad que permita que mientras se navega por los menús manteniendo pulsado bajara o subiera automáticamente el selector del menú de uno en uno para mayor comodidad al usuario.

**Comment by qu1que** [comment]
Sería interesante, sin duda, sobre todo en los submenús con mucho contenido

**Comment by bitstuffing** [comment]
Funcionalidad desarrollada en branch development, se mergeará con master.
