### ISSUE TITLE
[Spanish] Av. pag y Re. pag en el launcher

### ISSUE THREAD

**Issue by julenvitoria** [lemoncrest/kelboy-launcher#8]
Al ir a escoger una rom de entre todas las que podemos tener en la sd, si tenemos muchas por sistema hay que bajar hasta la que queramos... estaría bien implementar av. pag y re. pag con los botones 3º y 4º o 5º y 6º frontales para llegar antes al juego que queramos. También se podría añadir la opción de “Jump to...” al estilo de emulationstation para saltar a una letra que escojamos, aunque esto ya llevaría mucho más trabajo...

**Comment by bitstuffing** [comment]
me gusta la propuesta, aprovechar los botones que están sin uso para bajar de 5 en 5 o de 10 en 10

**Comment by bitstuffing** [comment]
Se utilizarán las teclas Z y T (las dos más cercanas a la cruceta teniendo la configuración de 6 botones) para tal fin, con ello se moverán de arriba o abajo el número máximo de elementos configurados como posibles en un menú (por defecto son 10 en el fichero settings.py)

**Comment by bitstuffing** [comment]
Implementado, se cierra issue.
