### ISSUE TITLE
[Spanish] Añadir funcionalidad para volver atrás sin llegar a BACK en el menú 

### ISSUE THREAD

**Issue by julenvitoria** [lemoncrest/kelboy-launcher#9]
Básicamente pues si se tienen or ejemplo 1000 roms y estas en la numero 358 por ejemplo tienes que ir hasta abajo o hasta arriba para volver atrás en el menú pulsando en BACK. Sería conveniente asignar a un botón esa funcionalidad y así no Heber que ir hasta un extremo del listado, podría ser un botón de disparo o select o start

**Comment by bitstuffing** [comment]
Funcionalidad demandada y aprobada, se implementará para ser utilizada la tecla B como atajo para ir al menú anterior.
